### ISSUE TITLE
Make it easy to build and test locally

### ISSUE THREAD

**Issue by jlebon** [dustymabe/fedora-coreos-ci#3]
We should strive to make the pipeline easy to hack on locally. Current issues that I've hit so far:

1. for some reason, in the `oc cluster up` case, I have to do:

```diff
--- a/Jenkinsfile
+++ b/Jenkinsfile
@@ -12,28 +12,30 @@ pipeline {
       spec:
         containers:
          - name: jnlp
-           image: docker-registry.default.svc:5000/fedora-coreos/jenkins-slave-base-centos7:latest
+           image: 172.30.1.1:5000/myproject/jenkins-slave-base-centos7:latest
          - name: coreos-assembler
-           image: docker-registry.default.svc:5000/fedora-coreos/dustymabe-coreos-assembler:latest
+           image: 172.30.1.1:5000/myproject/dustymabe-coreos-assembler:latest
```

to get the images to pull successfully. I've definitely hit this in the past too when hacking on [PACI](https://github.com/projectatomic/paci), though I don't remember right now how I've worked around it.

2. mounting the Duffy key & pushing artifacts: we don't want to do that locally, because we don't want to overwrite the artifacts in the first place. We need something like the dev mode in the RHCOS pipeline.

**Comment by dustymabe** [comment]
>     1. mounting the Duffy key & pushing artifacts

this is handled in #4
